feat: add main title layout
rockphin/gyeonhae-android pull request #42
Opened 2021-08-08 10:40 UTC by Gijuno

2021-08-08 10:42 UTC, Gijuno commented
additional works after #40 and #41 close

2021-08-08 11:47 UTC, nutyworks requested changes
Please reformat the layout file.
* There should be a space before `/>`.
* XML attributes should be aligned in alphabetical order.

2021-08-08 11:47 UTC, nutyworks commented on app/src/main/res/layout/layout_main_title.xml
> +        android:text="반갑습니다"
Please fix the hard-coded string.

2021-08-08 11:47 UTC, nutyworks commented on app/src/main/res/layout/layout_main_title.xml
> +        android:text="사용할 기능을 선택하세요"
Please fix the hard-coded string.

2021-08-08 11:47 UTC, nutyworks commented on app/src/main/res/layout/layout_main_title.xml
> +        android:layout_height="45dp"/>
`contentDescription` attribute is missing. Please consider adding it for better accessibility.

2021-08-09 14:09 UTC, nutyworks approved these changes

2021-08-09 14:27 UTC, merged