Implement inner activity
rockphin/gyeonhae-android pull request #52
Opened 2021-08-30 05:45 UTC by Gijuno

2021-08-30 14:49 UTC, nutyworks requested changes

2021-08-30 14:49 UTC, nutyworks commented on app/src/main/java/us/gijuno/gyeonhae/presentation/InnerActivitySelector.kt
> +    }
`result` is redundant.
```kt
return when (index) {
    0 -> "recognize"
    // ...
}
```

2021-08-30 14:49 UTC, nutyworks commented on app/src/main/java/us/gijuno/gyeonhae/presentation/InnerActivitySelector.kt
> +}
파일 자체가 왜 존재하는지 모르겠습니다. `result`의 접근자는 private인데 내부에서 사용하고 있는 것도 아닙니다. 그리고 위의 경우 enum class로 관리하는 것이 더 효율적으로 보입니다.

2021-08-30 14:49 UTC, nutyworks commented on app/src/main/java/us/gijuno/gyeonhae/presentation/InnerActivitySelector.kt
> +fun InnerActivitySelector(index: Int): String {
함수 이름은 소문자로 시작합니다.

2021-08-30 14:49 UTC, nutyworks commented on app/src/main/java/us/gijuno/gyeonhae/presentation/InnerActivity.kt
> +        }
text를 설정할 때 i18n이 고려되고 있지 않습니다. getString 함수를 사용해주세요.

2021-08-30 14:49 UTC, nutyworks commented on app/src/main/java/us/gijuno/gyeonhae/presentation/InnerActivity.kt
> +        val innerSubTitle = findViewById<TextView>(R.id.inner_subtitle)
`val innerSubtitle`

2021-08-30 14:49 UTC, nutyworks commented on app/src/main/java/us/gijuno/gyeonhae/presentation/InnerActivity.kt
> +        val buttonItemsList = mutableListOf<LayoutMenuButton>()
`val buttonItems` 또는 `val buttonItemList`

2021-08-30 14:49 UTC, nutyworks commented on app/src/main/java/us/gijuno/gyeonhae/presentation/InnerActivity.kt
> +        val activityStatus = intent.getStringExtra("index").toString()
`String?.toString()`을 사용하는 것보다는 null인 경우 return 하는 것이 더 적절해 보입니다.

2021-08-30 14:51 UTC, nutyworks commented
UI에서 줄바꿈, 정렬이 제대로 되어 있지 않고 버튼의 그림자가 잘려 있습니다. 설정 탭의 경우에는 다른 PR에서 작업해야 합니다.

2021-08-31 01:01 UTC, Gijuno commented on app/src/main/java/us/gijuno/gyeonhae/presentation/InnerActivitySelector.kt
> +    }
wow

2021-08-31 01:09 UTC, Gijuno commented on app/src/main/java/us/gijuno/gyeonhae/presentation/InnerActivity.kt
> +        }
아 맞네요 깜빡했네요

2021-08-31 01:25 UTC, Gijuno commented
> UI에서 줄바꿈, 정렬이 제대로 되어 있지 않고 버튼의 그림자가 잘려 있습니다. 설정 탭의 경우에는 #31 과 관련된 이슈입니다.

UI의 경우 추후 디자이너와 상의 후 작업할 예정이며, 설정 탭의 경우 #31 를 확인하지 못했습니다.. #31 에 관련해서는 기술 구현에 중점을 두도록 하겠습니다

2021-08-31 11:18 UTC, nutyworks commented on app/src/main/java/us/gijuno/gyeonhae/presentation/MainActivity.kt
> +    }
`enum class`로 관리해주세요...

2021-08-31 11:19 UTC, nutyworks requested changes

2021-08-31 11:19 UTC, nutyworks commented on app/src/main/java/us/gijuno/gyeonhae/presentation/InnerActivity.kt
> +class InnerActivity : AppCompatActivity() {
`BaseActivity` 상속받아서 써야 합니다.

2021-09-03 00:45 UTC, nutyworks approved these changes
빌드되면 머지 해주세요~

2021-09-03 05:44 UTC, merged